controller_list:
  - name: fake_arm_controller
    joints:
      - arm_lift_joint
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_upperarm_roll_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
      - arm_wrist_roll_joint
  - name: fake_gripper_controller
    joints:
      - l_gripper_joint
      - r_gripper_joint